/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuthProviderType = "google" | "oidc" | "saml";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ParallaxAgentRole = "lead" | "member";

export type ParallaxAgentStatus = "approved" | "denied" | "pending" | "revoked";

export type ParallaxAssignmentType = "project" | "task";

export type TaskBucket = "inbox" | "none" | "someday" | "waiting";

export type TaskPriority = "high" | "low" | "medium" | "urgent";

export type TaskStatus = "blocked" | "done" | "in_progress" | "in_review" | "todo";

export type TerminalSessionStatus = "active" | "connecting" | "disconnected" | "login_required" | "pending" | "terminated";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgentInvites {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  description: string | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  permissions: Generated<string[] | null>;
  revokedAt: Timestamp | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  usesCount: Generated<number>;
  usesRemaining: number | null;
  workspaceId: string;
}

export interface AgentMemories {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  source: string | null;
  spaceId: string | null;
  summary: string | null;
  tags: Json | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AgentReviewPrompts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  question: string;
  resolvedAt: Timestamp | null;
  source: string | null;
  spaceId: string;
  status: Generated<string>;
  weekKey: string;
  workspaceId: string;
}

export interface Attachments {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  mimeType: string | null;
  pageId: string | null;
  spaceId: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  type: AuthProviderType;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Billing {
  amount: Int8 | null;
  cancelAt: Timestamp | null;
  cancelAtPeriodEnd: boolean | null;
  canceledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currency: string | null;
  deletedAt: Timestamp | null;
  endedAt: Timestamp | null;
  id: Generated<string>;
  interval: string | null;
  metadata: Json | null;
  periodEndAt: Timestamp | null;
  periodStartAt: Timestamp;
  quantity: Int8 | null;
  status: string;
  stripeCustomerId: string | null;
  stripeItemId: string | null;
  stripePriceId: string | null;
  stripeProductId: string | null;
  stripeSubscriptionId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  selection: string | null;
  type: string | null;
  workspaceId: string;
}

export interface Goals {
  createdAt: Generated<Timestamp>;
  description: string | null;
  horizon: string;
  id: Generated<string>;
  keywords: Json | null;
  name: string;
  spaceId: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface McpApiKeys {
  createdAt: Generated<Timestamp>;
  hashedKey: string;
  id: string;
  lastUsedAt: Timestamp | null;
  name: string;
  userId: string;
  workspaceId: string;
}

export interface PageHistory {
  content: Json | null;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  pageId: string;
  slug: string | null;
  slugId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface Pages {
  agentAccessible: Generated<boolean | null>;
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  parentPageId: string | null;
  position: string | null;
  slugId: string;
  spaceId: string;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface ParallaxAgentActivity {
  activityType: string;
  agentId: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  pageId: string | null;
  projectId: string | null;
  taskId: string | null;
  workspaceId: string;
}

export interface ParallaxAgentActivityDaily {
  activityDate: Timestamp;
  activityType: string;
  agentId: string | null;
  count: Generated<number>;
  id: Generated<string>;
  sampleMetadata: Generated<Json | null>;
  workspaceId: string;
}

export interface ParallaxAgentAssignments {
  agentId: string;
  assignedAt: Generated<Timestamp | null>;
  assignedBy: string | null;
  assignmentType: ParallaxAssignmentType;
  id: Generated<string>;
  projectId: string | null;
  role: Generated<ParallaxAgentRole | null>;
  taskId: string | null;
  unassignedAt: Timestamp | null;
  workspaceId: string;
}

export interface ParallaxAgents {
  capabilities: string[];
  createdAt: Generated<Timestamp>;
  denialReason: string | null;
  description: string | null;
  endpoint: string | null;
  grantedPermissions: Generated<string[] | null>;
  id: string;
  inviteId: string | null;
  mcpApiKeyId: string | null;
  metadata: Generated<Json | null>;
  name: string;
  requestedAt: Generated<Timestamp | null>;
  requestedPermissions: string[];
  resolvedAt: Timestamp | null;
  resolvedBy: string | null;
  status: Generated<ParallaxAgentStatus>;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Projects {
  agentLive: Generated<boolean | null>;
  agentLiveChangedAt: Timestamp | null;
  agentLiveChangedBy: string | null;
  color: string | null;
  coverImage: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  endDate: Timestamp | null;
  homePageId: string | null;
  icon: string | null;
  id: Generated<string>;
  isArchived: Generated<boolean>;
  name: string;
  spaceId: string;
  startDate: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ProjectViews {
  config: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  name: string;
  projectId: string;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface ResearchJobs {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  goal: string | null;
  id: Generated<string>;
  logPageId: string | null;
  outputMode: Generated<string>;
  reportPageId: string | null;
  repoTargets: Json | null;
  sources: Json | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  timeBudgetMinutes: Generated<number>;
  topic: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface TaskBacklinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetTaskId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface TaskDependencies {
  createdAt: Generated<Timestamp>;
  dependsOnTaskId: string;
  id: Generated<string>;
  taskId: string;
}

export interface TaskGoalAssignments {
  createdAt: Generated<Timestamp>;
  goalId: string;
  id: Generated<string>;
  taskId: string;
}

export interface TaskLabelAssignments {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  labelId: string;
  taskId: string;
}

export interface TaskLabels {
  color: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Tasks {
  agentAccessible: boolean | null;
  agentLive: boolean | null;
  assigneeId: string | null;
  bucket: Generated<TaskBucket>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  dueDate: Timestamp | null;
  estimatedTime: number | null;
  id: Generated<string>;
  isCompleted: Generated<boolean>;
  pageId: string | null;
  pageTaskId: string | null;
  parentTaskId: string | null;
  position: string | null;
  priority: Generated<TaskPriority>;
  projectId: string | null;
  spaceId: string;
  status: Generated<TaskStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface TaskWatchers {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  taskId: string;
  userId: string;
}

export interface TerminalSessionLogs {
  content: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  logType: string;
  sessionId: string;
}

export interface TerminalSessions {
  agentId: string;
  cols: Generated<number | null>;
  connectedUserId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastActivityAt: Timestamp | null;
  metadata: Generated<Json | null>;
  rows: Generated<number | null>;
  runtimeEndpoint: string | null;
  runtimeSessionId: string;
  status: Generated<TerminalSessionStatus>;
  terminatedAt: Timestamp | null;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  password: string | null;
  role: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  billingEmail: string | null;
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  enforceSso: Generated<boolean>;
  hostname: string | null;
  id: Generated<string>;
  licenseKey: string | null;
  logo: string | null;
  name: string | null;
  plan: string | null;
  settings: Json | null;
  status: string | null;
  stripeCustomerId: string | null;
  trialEndAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  agentInvites: AgentInvites;
  agentMemories: AgentMemories;
  agentReviewPrompts: AgentReviewPrompts;
  attachments: Attachments;
  authAccounts: AuthAccounts;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  billing: Billing;
  comments: Comments;
  goals: Goals;
  groups: Groups;
  groupUsers: GroupUsers;
  mcpApiKeys: McpApiKeys;
  pageHistory: PageHistory;
  pages: Pages;
  parallaxAgentActivity: ParallaxAgentActivity;
  parallaxAgentActivityDaily: ParallaxAgentActivityDaily;
  parallaxAgentAssignments: ParallaxAgentAssignments;
  parallaxAgents: ParallaxAgents;
  projects: Projects;
  projectViews: ProjectViews;
  researchJobs: ResearchJobs;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  taskBacklinks: TaskBacklinks;
  taskDependencies: TaskDependencies;
  taskGoalAssignments: TaskGoalAssignments;
  taskLabelAssignments: TaskLabelAssignments;
  taskLabels: TaskLabels;
  tasks: Tasks;
  taskWatchers: TaskWatchers;
  terminalSessionLogs: TerminalSessionLogs;
  terminalSessions: TerminalSessions;
  users: Users;
  userTokens: UserTokens;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
