/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuthProviderType = "google" | "oidc" | "saml";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type TaskBucket = "inbox" | "none" | "someday" | "waiting";

export type TaskPriority = "high" | "low" | "medium" | "urgent";

export type TaskStatus = "blocked" | "done" | "in_progress" | "in_review" | "todo";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Attachments {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  deletedAt: Timestamp | null;
  fileExt: string;
  fileName: string;
  filePath: string;
  fileSize: Int8 | null;
  id: Generated<string>;
  mimeType: string | null;
  pageId: string | null;
  pageTaskId: string | null;
  spaceId: string | null;
  type: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AuthAccounts {
  authProviderId: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  workspaceId: string;
}

export interface AuthProviders {
  allowSignup: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  name: string;
  oidcClientId: string | null;
  oidcClientSecret: string | null;
  oidcIssuer: string | null;
  samlCertificate: string | null;
  samlUrl: string | null;
  type: AuthProviderType;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AgentMemories {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  source: string | null;
  spaceId: string | null;
  summary: string | null;
  tags: Json | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface AgentReviewPrompts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  question: string;
  resolvedAt: Timestamp | null;
  source: string | null;
  spaceId: string;
  status: Generated<string>;
  weekKey: string;
  workspaceId: string;
}

export interface ResearchJobs {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  goal: string | null;
  id: Generated<string>;
  logPageId: string | null;
  outputMode: Generated<string>;
  reportPageId: string | null;
  repoTargets: Json | null;
  sources: Json | null;
  spaceId: string;
  startedAt: Timestamp | null;
  status: Generated<string>;
  timeBudgetMinutes: Generated<number>;
  topic: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Goals {
  createdAt: Generated<Timestamp>;
  description: string | null;
  horizon: string;
  id: Generated<string>;
  keywords: Json | null;
  name: string;
  spaceId: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Backlinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetPageId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface TaskBacklinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  sourcePageId: string;
  targetTaskId: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Comments {
  content: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  pageId: string;
  parentCommentId: string | null;
  resolvedAt: Timestamp | null;
  selection: string | null;
  type: string | null;
  workspaceId: string;
}

export interface Groups {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  isDefault: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface GroupUsers {
  createdAt: Generated<Timestamp>;
  groupId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface McpApiKeys {
  createdAt: Generated<Timestamp>;
  hashedKey: string;
  id: string;
  lastUsedAt: Timestamp | null;
  name: string;
  userId: string;
  workspaceId: string;
}

export interface PageHistory {
  content: Json | null;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  lastUpdatedById: string | null;
  pageId: string;
  slug: string | null;
  slugId: string | null;
  spaceId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  version: number | null;
  workspaceId: string;
}

export interface Pages {
  content: Json | null;
  contributorIds: Generated<string[] | null>;
  coverPhoto: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  deletedById: string | null;
  icon: string | null;
  id: Generated<string>;
  isLocked: Generated<boolean>;
  lastUpdatedById: string | null;
  parentPageId: string | null;
  position: string | null;
  slugId: string;
  spaceId: string;
  textContent: string | null;
  title: string | null;
  tsv: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
  ydoc: Buffer | null;
}

export interface Projects {
  color: string | null;
  coverImage: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  endDate: Timestamp | null;
  homePageId: string | null;
  icon: string | null;
  id: Generated<string>;
  isArchived: Generated<boolean>;
  name: string;
  spaceId: string;
  startDate: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface ProjectViews {
  config: Json | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  name: string;
  projectId: string;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface SpaceMembers {
  addedById: string | null;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  groupId: string | null;
  id: Generated<string>;
  role: string;
  spaceId: string;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface Spaces {
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  defaultRole: Generated<string>;
  deletedAt: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
  workspaceId: string;
}

export interface TaskDependencies {
  createdAt: Generated<Timestamp>;
  dependsOnTaskId: string;
  id: Generated<string>;
  taskId: string;
}

export interface TaskLabelAssignments {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  labelId: string;
  taskId: string;
}

export interface TaskGoalAssignments {
  createdAt: Generated<Timestamp>;
  goalId: string;
  id: Generated<string>;
  taskId: string;
}

export interface TaskLabels {
  color: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Tasks {
  assigneeId: string | null;
  bucket: Generated<TaskBucket>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  creatorId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  dueDate: Timestamp | null;
  estimatedTime: number | null;
  id: Generated<string>;
  isCompleted: Generated<boolean>;
  pageId: string | null;
  parentTaskId: string | null;
  position: string | null;
  priority: Generated<TaskPriority>;
  projectId: string | null;
  spaceId: string;
  status: Generated<TaskStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface TaskWatchers {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  taskId: string;
  userId: string;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  deactivatedAt: Timestamp | null;
  deletedAt: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  id: Generated<string>;
  invitedById: string | null;
  lastActiveAt: Timestamp | null;
  lastLoginAt: Timestamp | null;
  locale: string | null;
  name: string | null;
  password: string | null;
  role: string | null;
  settings: Json | null;
  timezone: string | null;
  updatedAt: Generated<Timestamp>;
  workspaceId: string | null;
}

export interface UserTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  token: string;
  type: string;
  usedAt: Timestamp | null;
  userId: string;
  workspaceId: string | null;
}

export interface WorkspaceInvitations {
  createdAt: Generated<Timestamp>;
  email: string | null;
  groupIds: string[] | null;
  id: Generated<string>;
  invitedById: string | null;
  role: string;
  token: string;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface Workspaces {
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultRole: Generated<string>;
  defaultSpaceId: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  emailDomains: Generated<string[] | null>;
  hostname: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string | null;
  settings: Json | null;
  status: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  agentMemories: AgentMemories;
  agentReviewPrompts: AgentReviewPrompts;
  attachments: Attachments;
  researchJobs: ResearchJobs;
  authAccounts: AuthAccounts;
  authProviders: AuthProviders;
  backlinks: Backlinks;
  taskBacklinks: TaskBacklinks;
  comments: Comments;
  goals: Goals;
  groups: Groups;
  groupUsers: GroupUsers;
  mcpApiKeys: McpApiKeys;
  pageHistory: PageHistory;
  pages: Pages;
  projects: Projects;
  projectViews: ProjectViews;
  spaceMembers: SpaceMembers;
  spaces: Spaces;
  taskDependencies: TaskDependencies;
  taskGoalAssignments: TaskGoalAssignments;
  taskLabelAssignments: TaskLabelAssignments;
  taskLabels: TaskLabels;
  tasks: Tasks;
  taskWatchers: TaskWatchers;
  users: Users;
  userTokens: UserTokens;
  workspaceInvitations: WorkspaceInvitations;
  workspaces: Workspaces;
}
